name: Build and push to Amazon ECR
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      # Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Verify AWS credentials and region setup
      - name: Verify AWS CLI Configuration
        run: aws sts get-caller-identity

      # Log in to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Build and push Docker image to ECR
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.ECR_REGISTRY }}/offer-module-client:latest
          file: ./Dockerfile
