name: Build and push to Amazon ECR
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      # Log in to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}

      # Build and push Docker image to ECR
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.ECR_REGISTRY }}/offer-module-client-dev:latest
          file: ./Dockerfile
